### ISSUE TITLE
mods documentation 

### ISSUE THREAD

**Issue by AlsoInteresting** [brather1ng/RePoE#49]
When I follow your mods documentation to the letter, I can't find the correct translation.
This for the second part of this hybrid: https://pathofexile.fandom.com/wiki/Modifier:BleedDamage3
BleedDamage3 uses id "bleed_on_hit_with_attacks_%" in the translations. The stat has min=30 and max=30.
Only the first of the three conditions needs to be tested. Here are the conditions: 
{}: "Attacks cannot cause Bleeding"
{}: "Attacks cause Bleeding"
{"min": 100}:: "Attacks cause Bleeding"
{}:"Attacks have {0}% chance to cause Bleeding"

When going over these conditions, the first one matches.
But it should the last one. What am I missing?

**Comment by brather1ng** [comment]
> Only the first of the three conditions needs to be tested.

That is not correct. You'll have to check the conditions while using 0 as values for global_bleed_on_hit and cannot_cause_bleeding.

Then, the first entry does not match because cannot_cause_bleeding is 0, the second entry does not match because global_bleed_on_hit  is 0, the third entry does not match because bleed_on_hit_with_attacks_% is < 100 and then the last entry matches.

**Comment by AlsoInteresting** [comment]
The first condition for cannot_cause_bleeding is this:
{
    "max": 0,
    "min": 0,
    "negated": true
}
Cannot_cause_bleeding is 0 so that seems to match (min <= v <= max) 
Or did I misread a rule?

**Comment by brather1ng** [comment]
`"negated": true` means the match result is negated, so it doesn't match. This condition matches if cannot_cause_bleeding is not 0.

**Comment by AlsoInteresting** [comment]
Thanks for taking your time to explain.
