### ISSUE TITLE
Missing stat translation?

### ISSUE THREAD

**Issue by rasmuskl** [brather1ng/RePoE#5]
Are the stat_translations in data propertly updated?

Looks like the new stat from Arc is missing: `arc_damage_+%_final_for_each_remaining_chain`

**Comment by brather1ng** [comment]
The stat_translations are updated. But the GGPK's `stat_descriptions.txt` does not contain all translations, e.g. not the gem specific ones. I can't include those, because they would overwrite other translations to a gem-specific context (e.g. "Supported skills have ..."), see [the comment at the bottom of `stat_translations.py`](https://github.com/brather1ng/RePoE/blob/master/RePoE/stat_translations.py#L107) for more information.

I can include more stat translation files if you need those. `skill_stat_descriptions.txt` is probably the one containing the Arc stat. But that would again not cover all skills because there are even more specific files.

**Comment by rasmuskl** [comment]
Thanks for the quick reply.

I can grab the files myself, but it might be useful for future consumers of the data if they're available here. I would have found them then with repository search.

**Comment by brather1ng** [comment]
I've added all of them. If there's interest in a file containing the mapping from skill id to the respective translation file, I can add that.

**Comment by rasmuskl** [comment]
Perfect. Thanks. This is much more approachable than going full PyPoE 👍

**Comment by rasmuskl** [comment]
@brather1ng It looks like some of them are still missing, like `arc_enhanced_behaviour`.. Is this a special kind of stat that's flagged as hidden somehow?

If the mapping file is easy to do or add to `gems.json`, that'd also be neat.

**Comment by brather1ng** [comment]
Some stats don't have translations. I don't think there's any kind of flag to identify them, they simply aren't in the translation files.

> If the mapping file is easy to do or add to gems.json, that'd also be neat.

Added as `stat_translations_file` field in `gems.json`.

**Comment by rasmuskl** [comment]
Great. I'll try and stop bugging you now then :)

**Comment by brather1ng** [comment]
No problem, this wasn't really any work
